#!/usr/bin/env bash
# lh-harness-node entrypoint.
#
# Seeds a fleet-default .lh-harness/config.toml at the workspace root when one
# is absent (a per-repo .lh-harness/config.toml inside a checkout still wins —
# the harness loads config relative to the worker's cwd), then serves the web
# control API. The server refuses a non-loopback bind without a token, so
# LH_HARNESS_WEB_TOKEN is mandatory.
set -euo pipefail

: "${LH_HARNESS_WEB_TOKEN:?LH_HARNESS_WEB_TOKEN is required (server refuses 0.0.0.0 without a bearer token)}"

WORKSPACE_ROOT="${LH_NODE_WORKSPACE_ROOT:-/home/harness/work}"
RUNS_ROOT="${LH_NODE_RUNS_ROOT:-/home/harness/runs}"
PORT="${LH_NODE_PORT:-8799}"

mkdir -p "$WORKSPACE_ROOT" "$RUNS_ROOT"

CONFIG_DIR="$WORKSPACE_ROOT/.lh-harness"
CONFIG_FILE="$CONFIG_DIR/config.toml"

# Fleet defaults mirror the known-good CT110 values (cognizioware-how-to.md,
# TEMPLATE-litellm-qwen-local.md): manager 300 / executors 5400 / auditor 600,
# guard excludes for JS build dirs. All overridable via env at install time.
if [[ ! -f "$CONFIG_FILE" ]]; then
    mkdir -p "$CONFIG_DIR"
    GUARD_CSV="${LH_NODE_GUARD_EXCLUDE_PATHS:-node_modules,graphify-out,logs}"
    GUARD_TOML=$(printf '%s' "$GUARD_CSV" | awk -F',' '{
        out=""; for (i=1; i<=NF; i++) { if ($i != "") out = out (out=="" ? "" : ", ") "\"" $i "\"" }
        print "[" out "]" }')
    cat > "$CONFIG_FILE" <<EOF
# Generated by lh-harness-node entrypoint ($(date -u +%FT%TZ)).
# A per-repo .lh-harness/config.toml inside a workspace overrides this file.

[run]
agent = "${LH_NODE_AGENT:-claude_code}"
model = "${LH_NODE_MODEL:-kimi-k2.7-code:cloud}"
env = "local"
runs_root = "$RUNS_ROOT"
prompt_language = "${LH_NODE_PROMPT_LANGUAGE:-en}"
max_rounds = ${LH_NODE_MAX_ROUNDS:-25}
dashboard = false
guard_exclude_paths = $GUARD_TOML
mcp_add_dirs = []

[run.timeouts]
manager = ${LH_NODE_TIMEOUT_MANAGER:-300}
gui_executor = ${LH_NODE_TIMEOUT_GUI_EXECUTOR:-5400}
cli_executor = ${LH_NODE_TIMEOUT_CLI_EXECUTOR:-5400}
auditor = ${LH_NODE_TIMEOUT_AUDITOR:-600}

[run.roles.manager]
model = "${LH_NODE_MANAGER_MODEL:-${LH_NODE_MODEL:-kimi-k2.7-code:cloud}}"

[run.roles.executor]
model = "${LH_NODE_EXECUTOR_MODEL:-${LH_NODE_MODEL:-kimi-k2.7-code:cloud}}"

[run.roles.auditor]
model = "${LH_NODE_AUDITOR_MODEL:-kimi-k3:cloud}"
EOF
    echo "lh-harness-node: seeded $CONFIG_FILE"
fi

# Fleet reporting is configured entirely from the environment.  When unset,
# the web server starts without the reporter and behaves as before.
export LH_HARNESS_FLEET_URL="${LH_HARNESS_FLEET_URL:-}"
export LH_HARNESS_FLEET_NODE="${LH_HARNESS_FLEET_NODE:-}"
export LH_HARNESS_FLEET_KEY="${LH_HARNESS_FLEET_KEY:-}"
export LH_HARNESS_FLEET_LABELS="${LH_HARNESS_FLEET_LABELS:-}"

exec lh-harness web \
    --host 0.0.0.0 \
    --port "$PORT" \
    --runs-root "$RUNS_ROOT" \
    --workspace-root "$WORKSPACE_ROOT" \
    --no-open \
    --auth-token "$LH_HARNESS_WEB_TOKEN"
